version: '3.7'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - "./data:/var/lib/mysql"
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tigger1234
      MYSQL_DATABASE: solomon_tigger
      MYSQL_USER: tigger
      MYSQL_PASSWORD: tigger1234
    ports:
      - "3306:3306"
